### PR TITLE
Update Quantiler.java

### PR DESCRIPTION
**Pull request by ltalal**
Fixed formula for linear interpolation in Quantiler for marker height decreasing.

### CODE REVIEW

**Comment by dhale** [comment]
I do not have a test, but have reviewed the original paper on which the code is based, and the proposed change is correct. Nice find!

**Comment by dhale** [comment]
Here is a link to that paper, in case anyone wants to check.
https://www.cse.wustl.edu/~jain/papers/ftp/psqr.pdf

**Comment by ltalal** [comment]
Dave, thanks for quick reply! I see that you've commited the change to master already https://github.com/MinesJTK/jtk/commit/00c4a2b2dff154831222c0174f1f31e03a5ea7e4 
So probably this PR may be closed

**Comment by dhale** [comment]
Chris was requested for review! Where are you, buddy? Want me to hit big green "Merge pull request" button?

**Comment by chrisengelsma** [comment]
Thanks for the poke, @dhale !

**Pull request merged**
